language: c++
script:
matrix: 
  include: 
  - env: TARGET_OS=android
    os: linux
    script:
    - ./cmakeify --group-id com.github.jomof --artifact-id re2 --target-version ${TRAVIS_TAG:-0.0.0} --target-os android
    - ./cdep
    - ./cmakeify -wf .cdep/examples/cmake --target-os android
    
  - env: TARGET_OS=linux
    os: linux
    script:
    - ./cmakeify --group-id com.github.jomof --artifact-id re2 --target-version ${TRAVIS_TAG:-0.0.0} --target-os linux
    - ./cdep
    - ./cmakeify -wf .cdep/examples/cmake --target-os linux
    
  - env: TARGET_OS=iOS
    os: osx
    script:
    - ./cmakeify --group-id com.github.jomof --artifact-id re2 --target-version ${TRAVIS_TAG:-0.0.0} --target-os iOS
    - ./cdep
    - ./cmakeify -wf .cdep/examples/cmake --target-os iOS
 
