language: c++
script:
matrix: 
  include: 
  - env: TARGET_OS=android
    os: linux
    script:
    - ./cmakeify
    - ./cdep fullfill build/Android ${TRAVIS_TAG:-0.0.0} cdep-manifest.yml 
    - ./cdep
    - ./cmakeify -wf .cdep/examples/cmake
    - git clone https://github.com/jomof/tools
    - tools/github_release_folder jomof re2 .cdep/fullfill/output/layout
    
#  - env: TARGET_OS=linux
#    os: linux
#    addons:
#      apt:
#        sources:
#        - ubuntu-toolchain-r-test
#        packages:
#        - gcc-4.8
#        - g++-4.8
#    script:
#    - ./cmakeify --group-id com.github.jomof --artifact-id re2 --target-version ${TRAVIS_TAG:-0.0.0} --target-os linux
#    - ./cdep
#    - ./cmakeify -wf .cdep/examples/cmake --target-os linux
    
#  - env: TARGET_OS=iOS
#    os: osx
#    script:
#    - ./cmakeify --group-id com.github.jomof --artifact-id re2 --target-version ${TRAVIS_TAG:-0.0.0} --target-os iOS
#    - ./cdep
#    - ./cmakeify -wf .cdep/examples/cmake --target-os iOS
