
{% set version = environ.get('GIT_DESCRIBE_TAG').lstrip('v') %}
{% set number = GIT_DESCRIBE_NUMBER %}

package:
  name: ea-re2-pkg
  version: {{ version }}

build:
  number: {{ number }}

about:
  home: https://github.com/gottingen/re2
  license: Apache License 2
  license_family: APACHE
  license_file: LICENSE
  summary: A library for c++ based libraries and rpc libraries

source:
  git_url: ../

outputs:
  - name: ea-re2
    script: bld.sh   # [not win]
    script: bld.bat  # [win]
    build:
      string: "h{{ GIT_DESCRIBE_HASH }}_{{ number }}"
      run_exports:
        - {{ pin_compatible('ea-re2', exact=True) }}
    requirements:
      build:
      host:
      run:
    test:
      commands:
        - test -f $PREFIX/lib/libre2.a
      #  - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
      #  - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]
